### ISSUE TITLE
批量tokenize的时候报错

### ISSUE THREAD

**Issue by yayaQAQ** [JunnYu/ChineseBert_pytorch#2]
![image](https://user-images.githubusercontent.com/20497531/134615442-e8d916f2-578b-44fd-a299-9ecfbe62d262.png)
![image](https://user-images.githubusercontent.com/20497531/134615476-8a689930-dfde-450f-a933-dd0434c0beb6.png)

**Comment by yayaQAQ** [comment]
我加上了padding的，但是好像不识别这个padding参数

**Comment by JunnYu** [comment]
安装github上最新的代码，才能运行成功。
