### ISSUE TITLE
老哥请问这个怎么做文本分类

### ISSUE THREAD

**Issue by SanForfive** [JunnYu/ChineseBert_pytorch#3]

**Comment by JunnYu** [comment]
首先你要知道huggingface仓库的模型如何进行文本分类，然后你只要将里面的模型替换成这个仓库的chinesebert模型就可以进行训练了，之后等我有时间写一个简单的分类模型。

**Comment by SanForfive** [comment]
okok感谢感谢

**Comment by JunnYu** [comment]
@SanForfive 
现在已经添加了`tnews文本分类`的例子了。
请查看https://github.com/JunnYu/ChineseBert_pytorch/tree/main/examples/tnews

**Comment by SanForfive** [comment]
> @SanForfive 现在已经添加了`tnews文本分类`的例子了。 请查看https://github.com/JunnYu/ChineseBert_pytorch/tree/main/examples/tnews

okok，像老哥学习
